---
title: "Exploration of over-estimation in simulated single cell data (replicate 1)"
author: "Yusha Liu"
header-includes:
date: "2021-4-27"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---


## Gene examples with over-estimation in replicate 1
```{r warning=FALSE, message=FALSE}
setwd("../simulations_sc/setting4/")
sample.info <- readRDS("signal_v2_data/sample_info.Rds")
cols.trt <- readRDS("sim_condition_colors.Rds")
trts <- names(cols.trt)
source("plot_by_gene.R")

### look at replicate 1
iter = 1

### read in data
data <- readRDS(paste0("signal_v2_data/raw_data", iter, ".Rds"))
beta <- data$beta
R <- ncol(beta)
  
### aggregate count data and size factors over conditions
scdata <- data$X
si <- readRDS(paste0("signal_v2_output/glmpca_rep_", iter, ".Rds"))$si
data.jr <- matrix(NA, nrow=nrow(scdata), ncol=R)
rownames(data.jr) <- rownames(scdata)
colnames(data.jr) <- trts
s <- rep(NA, R)
names(s) <- trts
  
for(r in 1:length(trts)){
  data.tmp <- scdata[, sample.info$sample==trts[r]]
  data.jr[,r] <- Matrix::rowSums(data.tmp)
  s[r] <- sum(si[sample.info$sample==trts[r]])
}
  
s <- s/min(s)
  
# load in the mash fit without common baseline
mash.fit <- readRDS(paste0("signal_v2_output/mash_cb_rep_", iter, ".Rds"))
  
# load poisson mash with ruv
post <- readRDS(paste0("signal_v2_output/pois_mash_ruv_posterior_rep_", iter, ".Rds"))

```


```{r warning=FALSE, message=FALSE}
plot_by_gene(data.jr, s, scdata, si, sample.info, res.mash.cb=mash.fit$result, res.pois.ruv=post, genename="Alox5ap", cols.trt=cols.trt) 
```


```{r warning=FALSE, message=FALSE}
plot_by_gene(data.jr, s, scdata, si, sample.info, res.mash.cb=mash.fit$result, res.pois.ruv=post, genename="Cnih4", cols.trt=cols.trt) 
```

```{r warning=FALSE, message=FALSE}
plot_by_gene(data.jr, s, scdata, si, sample.info, res.mash.cb=mash.fit$result, res.pois.ruv=post, genename="Zbtb8os", cols.trt=cols.trt) 
```

```{r warning=FALSE, message=FALSE}
plot_by_gene(data.jr, s, scdata, si, sample.info, res.mash.cb=mash.fit$result, res.pois.ruv=post, genename="Ier5", cols.trt=cols.trt) 
```

```{r warning=FALSE, message=FALSE}
plot_by_gene(data.jr, s, scdata, si, sample.info, res.mash.cb=mash.fit$result, res.pois.ruv=post, genename="Cebpg", cols.trt=cols.trt) 
```

```{r warning=FALSE, message=FALSE}
plot_by_gene(data.jr, s, scdata, si, sample.info, res.mash.cb=mash.fit$result, res.pois.ruv=post, genename="Jund", cols.trt=cols.trt) 
```

```{r warning=FALSE, message=FALSE}
plot_by_gene(data.jr, s, scdata, si, sample.info, res.mash.cb=mash.fit$result, res.pois.ruv=post, genename="Cotl1", cols.trt=cols.trt) 
```

```{r warning=FALSE, message=FALSE}
plot_by_gene(data.jr, s, scdata, si, sample.info, res.mash.cb=mash.fit$result, res.pois.ruv=post, genename="Rab11a", cols.trt=cols.trt) 
```

